[package]
name = "verify"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
edition = "2018"

[dev-dependencies]
stdarch-test = { git = "https://github.com/rust-lang/stdarch.git"  }
packed_simd = { package = "packed_simd_2", path = "../.." }
cfg-if = "^0.1"
paste = "^0.1.3"
